import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        sidebar: "var(--color-sidebar)",
        "sidebar-hover": "var(--color-sidebar-hover)",
        "sidebar-active": "var(--color-sidebar-active)",
        "sidebar-text": "var(--color-sidebar-text)",
        "sidebar-text-muted": "var(--color-sidebar-text-muted)",
        "sidebar-divider": "var(--color-sidebar-divider)",
        page: "var(--color-page)",
        "page-alt": "var(--color-page-alt)",
        "bg-secondary": "var(--color-bg-secondary)",
        "bg-tertiary": "var(--color-bg-tertiary)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-inverse": "var(--color-text-inverse)",
        border: "var(--color-border)",
        "border-dark": "var(--color-border-dark)",
        success: "var(--color-success)",
        "success-bg": "var(--color-success-bg)",
        warning: "var(--color-warning)",
        "warning-bg": "var(--color-warning-bg)",
        danger: "var(--color-danger)",
        "danger-bg": "var(--color-danger-bg)",
        info: "var(--color-info)",
        "info-bg": "var(--color-info-bg)",
        brand: {
          50: "var(--color-brand-50)",
          100: "var(--color-brand-100)",
          200: "var(--color-brand-200)",
          300: "var(--color-brand-300)",
          400: "var(--color-brand-400)",
          500: "var(--color-brand-500)",
          600: "var(--color-brand-600)",
          700: "var(--color-brand-700)",
          800: "var(--color-brand-800)",
          900: "var(--color-brand-900)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Geist", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        mono: ["var(--font-mono)", "Geist Mono", "SF Mono", "Consolas", "monospace"],
      },
      borderRadius: {
        DEFAULT: "6px",
        sm: "3px",
        md: "4px",
        lg: "6px",
        xl: "8px",
      },
      spacing: {
        "1.5": "6px",
        "2.5": "10px",
        "3.5": "14px",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        elevated: "var(--shadow-elevated)",
        modal: "var(--shadow-modal)",
        toast: "var(--shadow-toast)",
      },
      fontSize: {
        display: ["24px", { lineHeight: "1.3", fontWeight: "700", letterSpacing: "-0.02em" }],
        "heading-1": ["18px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "-0.01em" }],
        "heading-2": ["15px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-small": ["13px", { lineHeight: "1.4" }],
        caption: ["12px", { lineHeight: "1.3", fontWeight: "500" }],
        label: ["11px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "0.05em" }],
        micro: ["10px", { lineHeight: "1.2", fontWeight: "600", letterSpacing: "0.04em" }],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
