import { defineTheme } from "../components/ui/theme";

/** Generated by Balsa UI. Edit this definition in your application. */
export const seOrganizeMaisDesignSystemTheme = defineTheme({
  "id": "se-organize-mais-design-system",
  "name": "Se Organize Mais Design System",
  "extends": "modern-flat",
  "options": {
    "typography": "modern",
    "size": "compact",
    "spacing": "balanced",
    "border": "soft",
    "elevation": "soft",
    "motion": "fluid",
    "material": "glass"
  },
  "overrides": {
    "tokens": {
      "typography": {
        "titleFonts": [
          "Raleway",
          "sans-serif"
        ],
        "bodyFonts": [
          "Inter",
          "sans-serif"
        ],
        "controlFonts": [
          "Inter",
          "sans-serif"
        ]
      },
      "radius": {
        "control": 12,
        "surface": 21,
        "panel": 27,
        "badge": 9999,
        "toggle": 9999,
        "codeControl": 8
      }
    }
  }
});
